[project]
name = "static"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cryptography>=46.0.3",
    "flask>=3.1.2",
    "pycryptodome>=3.23.0",
    "requests>=2.32.5",
    "websockets>=15.0.1",
]
